In [4]:
import pandas as pd
import numpy as np
import os

In [ ]:
# need to do this pip install to read the older version of STATA file used
pip install pyreadstat

Collecting pyreadstat
  Downloading pyreadstat-1.3.7-cp313-cp313-macosx_11_0_arm64.whl.metadata (1.2 kB)
Collecting narwhals>=2.10.1 (from pyreadstat)
  Downloading narwhals-2.27.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pyreadstat) (2.3.3)
Downloading pyreadstat-1.3.7-cp313-cp313-macosx_11_0_arm64.whl (804 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 804.8/804.8 kB 18.0 MB/s eta 0:00:00
Downloading narwhals-2.27.1-py3-none-any.whl (483 kB)
Installing collected packages: narwhals, pyreadstat
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pyreadstat]
Successfully installed narwhals-2.27.1 pyreadstat-1.3.7

[notice] A new release of pip is available: 25.1.1 -> 26.2.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pyreadstat

In [ ]:
df, surveys = pyreadstat.read_dta('Datos del hogar y la vivienda.dta', encoding="latin1") #use encoding'"latin1" to read accents on letters

In [ ]:
print(surveys.column_labels) #get the column names/indicator codes

['PERIODO', None, None, 'DIRECTORIO', 'SECUENCIA_P', None, None, 'AREA', None, None, None, 'P4000', 'P4010', 'P4020', 'P4030S1', 'P4030S1A1', 'P4030S2', 'P4030S3', 'P4030S4', 'P4030S4A1', 'P4030S5', 'P70', 'P5000', 'P5010', 'P5020', 'P5030', 'P5040', 'P5050', 'P5070', 'P5080', 'P5090', 'P5090S1', 'P5100', 'P5110', 'P5130', 'P5140', 'P5222S1', 'P5222S2', 'P5222S3', 'P5222S4', 'P5222S5', 'P5222S6', 'P5222S7', 'P5222S8', 'P5222S9', 'P5222S10', 'P5222S8A1', 'P6008']

In [ ]:
# df, surveys = pyreadstat.read_dta("Gastos semanales Rural - Capitulo C.dta", apply_value_formats=True)

In [ ]:
# print(surveys.column_labels)

['DIRECTORIO', 'SECUENCIA_ENCUESTA', 'SECUENCIA_P', 'ORDEN', 'CARACTERISTICAS DEL GASTO EN ALIMENTOS DE LOS HOGARES\r\n1. Alimentos o grupos de', 'Frecuencia de Compra', '¿Cuál fue el valor de la última compra?', '¿Compró este alimento o grupo de alimentos durante la semana pasada (de lunes a', 'Factor de Expansión']

In [9]:
print(surveys)

metadata_container(column_names=['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'HOGAR', 'REGIS', 'AREA', 'CLASE', 'FEX_C18', 'DPTO', 'P4000', 'P4010', 'P4020', 'P4030S1', 'P4030S1A1', 'P4030S2', 'P4030S3', 'P4030S4', 'P4030S4A1', 'P4030S5', 'P70', 'P5000', 'P5010', 'P5020', 'P5030', 'P5040', 'P5050', 'P5070', 'P5080', 'P5090', 'P5090S1', 'P5100', 'P5110', 'P5130', 'P5140', 'P5222S1', 'P5222S2', 'P5222S3', 'P5222S4', 'P5222S5', 'P5222S6', 'P5222S7', 'P5222S8', 'P5222S9', 'P5222S10', 'P5222S8A1', 'P6008'], column_labels=['PERIODO', None, None, 'DIRECTORIO', 'SECUENCIA_P', None, None, 'AREA', None, None, None, 'P4000', 'P4010', 'P4020', 'P4030S1', 'P4030S1A1', 'P4030S2', 'P4030S3', 'P4030S4', 'P4030S4A1', 'P4030S5', 'P70', 'P5000', 'P5010', 'P5020', 'P5030', 'P5040', 'P5050', 'P5070', 'P5080', 'P5090', 'P5090S1', 'P5100', 'P5110', 'P5130', 'P5140', 'P5222S1', 'P5222S2', 'P5222S3', 'P5222S4', 'P5222S5', 'P5222S6', 'P5222S7', 'P5222S8', 'P5222S9', 'P5222S10', 'P5222S8A1', 'P6008'], column_names_to_labels={'PERIODO': 'PERIODO', 'MES': None, 'PER': None, 'DIRECTORIO': 'DIRECTORIO', 'SECUENCIA_P': 'SECUENCIA_P', 'HOGAR': None, 'REGIS': None, 'AREA': 'AREA', 'CLASE': None, 'FEX_C18': None, 'DPTO': None, 'P4000': 'P4000', 'P4010': 'P4010', 'P4020': 'P4020', 'P4030S1': 'P4030S1', 'P4030S1A1': 'P4030S1A1', 'P4030S2': 'P4030S2', 'P4030S3': 'P4030S3', 'P4030S4': 'P4030S4', 'P4030S4A1': 'P4030S4A1', 'P4030S5': 'P4030S5', 'P70': 'P70', 'P5000': 'P5000', 'P5010': 'P5010', 'P5020': 'P5020', 'P5030': 'P5030', 'P5040': 'P5040', 'P5050': 'P5050', 'P5070': 'P5070', 'P5080': 'P5080', 'P5090': 'P5090', 'P5090S1': 'P5090S1', 'P5100': 'P5100', 'P5110': 'P5110', 'P5130': 'P5130', 'P5140': 'P5140', 'P5222S1': 'P5222S1', 'P5222S2': 'P5222S2', 'P5222S3': 'P5222S3', 'P5222S4': 'P5222S4', 'P5222S5': 'P5222S5', 'P5222S6': 'P5222S6', 'P5222S7': 'P5222S7', 'P5222S8': 'P5222S8', 'P5222S9': 'P5222S9', 'P5222S10': 'P5222S10', 'P5222S8A1': 'P5222S8A1', 'P6008': 'P6008'}, file_encoding=None, file_label=None, number_columns=48, number_rows=25010, variable_value_labels={}, value_labels={}, variable_to_label={}, notes=[], original_variable_types={'PERIODO': '%9.0g', 'MES': '%2s', 'PER': '%12.0g', 'DIRECTORIO': '%16.0g', 'SECUENCIA_P': '%6.0g', 'HOGAR': '%12.0g', 'REGIS': '%2s', 'AREA': '%2s', 'CLASE': '%2s', 'FEX_C18': '%12.0g', 'DPTO': '%2s', 'P4000': '%6.0g', 'P4010': '%6.0g', 'P4020': '%6.0g', 'P4030S1': '%6.0g', 'P4030S1A1': '%6.0g', 'P4030S2': '%6.0g', 'P4030S3': '%6.0g', 'P4030S4': '%6.0g', 'P4030S4A1': '%6.0g', 'P4030S5': '%6.0g', 'P70': '%6.0g', 'P5000': '%4.0g', 'P5010': '%6.0g', 'P5020': '%4.0g', 'P5030': '%4.0g', 'P5040': '%4.0g', 'P5050': '%4.0g', 'P5070': '%4.0g', 'P5080': '%4.0g', 'P5090': '%4.0g', 'P5090S1': '%1000s', 'P5100': '%13.0g', 'P5110': '%21.0g', 'P5130': '%13.0g', 'P5140': '%13.0g', 'P5222S1': '%13.0g', 'P5222S2': '%13.0g', 'P5222S3': '%13.0g', 'P5222S4': '%13.0g', 'P5222S5': '%13.0g', 'P5222S6': '%13.0g', 'P5222S7': '%13.0g', 'P5222S8': '%13.0g', 'P5222S9': '%13.0g', 'P5222S10': '%13.0g', 'P5222S8A1': '%1000s', 'P6008': '%3.0g'}, original_variable_informats={'PERIODO': None, 'MES': None, 'PER': None, 'DIRECTORIO': None, 'SECUENCIA_P': None, 'HOGAR': None, 'REGIS': None, 'AREA': None, 'CLASE': None, 'FEX_C18': None, 'DPTO': None, 'P4000': None, 'P4010': None, 'P4020': None, 'P4030S1': None, 'P4030S1A1': None, 'P4030S2': None, 'P4030S3': None, 'P4030S4': None, 'P4030S4A1': None, 'P4030S5': None, 'P70': None, 'P5000': None, 'P5010': None, 'P5020': None, 'P5030': None, 'P5040': None, 'P5050': None, 'P5070': None, 'P5080': None, 'P5090': None, 'P5090S1': None, 'P5100': None, 'P5110': None, 'P5130': None, 'P5140': None, 'P5222S1': None, 'P5222S2': None, 'P5222S3': None, 'P5222S4': None, 'P5222S5': None, 'P5222S6': None, 'P5222S7': None, 'P5222S8': None, 'P5222S9': None, 'P5222S10': None, 'P5222S8A1': None, 'P6008': None}, readstat_variable_types={'PERIODO': 'double', 'MES': 'string', 'PER': 'double', 'DIRECTORIO': 'double', 'SECUENCIA_P': 'double', 'HOGAR': 'double', 'REGIS': 'string', 'AREA': 'string', 'CLASE': 'string', 'FEX_C18': 'double', 'DPTO': 'string', 'P4000': 'double', 'P4010': 'double', 'P4020': 'double', 'P4030S1': 'double', 'P4030S1A1': 'double', 'P4030S2': 'double', 'P4030S3': 'double', 'P4030S4': 'double', 'P4030S4A1': 'double', 'P4030S5': 'double', 'P70': 'double', 'P5000': 'double', 'P5010': 'double', 'P5020': 'double', 'P5030': 'double', 'P5040': 'double', 'P5050': 'double', 'P5070': 'double', 'P5080': 'double', 'P5090': 'double', 'P5090S1': 'string', 'P5100': 'double', 'P5110': 'double', 'P5130': 'double', 'P5140': 'double', 'P5222S1': 'double', 'P5222S2': 'double', 'P5222S3': 'double', 'P5222S4': 'double', 'P5222S5': 'double', 'P5222S6': 'double', 'P5222S7': 'double', 'P5222S8': 'double', 'P5222S9': 'double', 'P5222S10': 'double', 'P5222S8A1': 'string', 'P6008': 'double'}, table_name=None, missing_ranges={}, missing_user_values={}, variable_storage_width={'PERIODO': 8, 'MES': 3, 'PER': 8, 'DIRECTORIO': 8, 'SECUENCIA_P': 8, 'HOGAR': 8, 'REGIS': 3, 'AREA': 3, 'CLASE': 3, 'FEX_C18': 8, 'DPTO': 3, 'P4000': 8, 'P4010': 8, 'P4020': 8, 'P4030S1': 8, 'P4030S1A1': 8, 'P4030S2': 8, 'P4030S3': 8, 'P4030S4': 8, 'P4030S4A1': 8, 'P4030S5': 8, 'P70': 8, 'P5000': 8, 'P5010': 8, 'P5020': 8, 'P5030': 8, 'P5040': 8, 'P5050': 8, 'P5070': 8, 'P5080': 8, 'P5090': 8, 'P5090S1': 1001, 'P5100': 8, 'P5110': 8, 'P5130': 8, 'P5140': 8, 'P5222S1': 8, 'P5222S2': 8, 'P5222S3': 8, 'P5222S4': 8, 'P5222S5': 8, 'P5222S6': 8, 'P5222S7': 8, 'P5222S8': 8, 'P5222S9': 8, 'P5222S10': 8, 'P5222S8A1': 1001, 'P6008': 8}, variable_display_width={'PERIODO': 9, 'MES': 2, 'PER': 12, 'DIRECTORIO': 16, 'SECUENCIA_P': 6, 'HOGAR': 12, 'REGIS': 2, 'AREA': 2, 'CLASE': 2, 'FEX_C18': 12, 'DPTO': 2, 'P4000': 6, 'P4010': 6, 'P4020': 6, 'P4030S1': 6, 'P4030S1A1': 6, 'P4030S2': 6, 'P4030S3': 6, 'P4030S4': 6, 'P4030S4A1': 6, 'P4030S5': 6, 'P70': 6, 'P5000': 4, 'P5010': 6, 'P5020': 4, 'P5030': 4, 'P5040': 4, 'P5050': 4, 'P5070': 4, 'P5080': 4, 'P5090': 4, 'P5090S1': 1000, 'P5100': 13, 'P5110': 21, 'P5130': 13, 'P5140': 13, 'P5222S1': 13, 'P5222S2': 13, 'P5222S3': 13, 'P5222S4': 13, 'P5222S5': 13, 'P5222S6': 13, 'P5222S7': 13, 'P5222S8': 13, 'P5222S9': 13, 'P5222S10': 13, 'P5222S8A1': 1000, 'P6008': 3}, variable_alignment={'PERIODO': 'right', 'MES': 'right', 'PER': 'right', 'DIRECTORIO': 'right', 'SECUENCIA_P': 'right', 'HOGAR': 'right', 'REGIS': 'right', 'AREA': 'right', 'CLASE': 'right', 'FEX_C18': 'right', 'DPTO': 'right', 'P4000': 'right', 'P4010': 'right', 'P4020': 'right', 'P4030S1': 'right', 'P4030S1A1': 'right', 'P4030S2': 'right', 'P4030S3': 'right', 'P4030S4': 'right', 'P4030S4A1': 'right', 'P4030S5': 'right', 'P70': 'right', 'P5000': 'right', 'P5010': 'right', 'P5020': 'right', 'P5030': 'right', 'P5040': 'right', 'P5050': 'right', 'P5070': 'right', 'P5080': 'right', 'P5090': 'right', 'P5090S1': 'right', 'P5100': 'right', 'P5110': 'right', 'P5130': 'right', 'P5140': 'right', 'P5222S1': 'right', 'P5222S2': 'right', 'P5222S3': 'right', 'P5222S4': 'right', 'P5222S5': 'right', 'P5222S6': 'right', 'P5222S7': 'right', 'P5222S8': 'right', 'P5222S9': 'right', 'P5222S10': 'right', 'P5222S8A1': 'right', 'P6008': 'right'}, variable_measure={'PERIODO': 'unknown', 'MES': 'unknown', 'PER': 'unknown', 'DIRECTORIO': 'unknown', 'SECUENCIA_P': 'unknown', 'HOGAR': 'unknown', 'REGIS': 'unknown', 'AREA': 'unknown', 'CLASE': 'unknown', 'FEX_C18': 'unknown', 'DPTO': 'unknown', 'P4000': 'unknown', 'P4010': 'unknown', 'P4020': 'unknown', 'P4030S1': 'unknown', 'P4030S1A1': 'unknown', 'P4030S2': 'unknown', 'P4030S3': 'unknown', 'P4030S4': 'unknown', 'P4030S4A1': 'unknown', 'P4030S5': 'unknown', 'P70': 'unknown', 'P5000': 'unknown', 'P5010': 'unknown', 'P5020': 'unknown', 'P5030': 'unknown', 'P5040': 'unknown', 'P5050': 'unknown', 'P5070': 'unknown', 'P5080': 'unknown', 'P5090': 'unknown', 'P5090S1': 'unknown', 'P5100': 'unknown', 'P5110': 'unknown', 'P5130': 'unknown', 'P5140': 'unknown', 'P5222S1': 'unknown', 'P5222S2': 'unknown', 'P5222S3': 'unknown', 'P5222S4': 'unknown', 'P5222S5': 'unknown', 'P5222S6': 'unknown', 'P5222S7': 'unknown', 'P5222S8': 'unknown', 'P5222S9': 'unknown', 'P5222S10': 'unknown', 'P5222S8A1': 'unknown', 'P6008': 'unknown'}, creation_time=datetime.datetime(1970, 1, 1, 1, 0), modification_time=datetime.datetime(1970, 1, 1, 1, 0), mr_sets={})

In [11]:
df.head()

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,HOGAR,REGIS,AREA,CLASE,FEX_C18,...,P5222S3,P5222S4,P5222S5,P5222S6,P5222S7,P5222S8,P5222S9,P5222S10,P5222S8A1,P6008
0,20230208.0,02,2023.0,7338343.0,1.0,1.0,01,,2,287.801261,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,,3.0
1,20230208.0,02,2023.0,7338344.0,1.0,1.0,01,,2,371.632104,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,,4.0
2,20230208.0,02,2023.0,7338345.0,1.0,1.0,01,,2,333.791029,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,,4.0
3,20230208.0,02,2023.0,7338346.0,1.0,1.0,01,,2,259.600384,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,,3.0
4,20230208.0,02,2023.0,7338347.0,1.0,1.0,01,,2,215.021799,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,,1.0

In [14]:
df['P5090'].value_counts()

P5090
3.0    10226
1.0     7807
4.0     4313
5.0     1032
2.0      907
6.0      634
7.0       91
Name: count, dtype: int64

In [ ]:
df['PERIODO'] #date format = YEAR/MONTH/WEEK in the year

0        20230208.0
1        20230208.0
2        20230208.0
3        20230208.0
4        20230208.0
            ...
25005    20230208.0
25006    20230208.0
25007    20230208.0
25008    20230208.0
25009    20230208.0
Name: PERIODO, Length: 25010, dtype: float64

In [ ]:
df, surveys = pyreadstat.read_dta('col23n2.dta', encoding="latin1") #this is reading in the STATA file provided from UN ECLAC

In [19]:
df

,mes,directorio,secuencia_p,regis_r010,p4000,p4010,p4020,p4030s1,p4030s1a1,p4030s2,...,impa_i,iof3h_i,iof3i_i,iof1_i,trimestre,pctalqr,pctalqu,c_merge,ingtotug_i,ingtotugarr_i
0,01,7309060,1,01,1,1,4,1,2,2,...,0,0,0,0,1,0.43,0.41,3,2200000.0,2200000.0
1,01,7309060,1,01,1,1,4,1,2,2,...,1200000,0,0,0,1,0.43,0.41,3,2200000.0,2200000.0
2,01,7309060,1,01,1,1,4,1,2,2,...,0,0,0,0,1,0.43,0.41,3,2200000.0,2200000.0
3,01,7309061,1,01,1,1,4,1,2,1,...,2200000,0,0,0,1,0.43,0.41,3,3130000.0,3130000.0
4,01,7309061,1,01,1,1,4,1,2,1,...,650000,0,0,0,1,0.43,0.41,3,3130000.0,3130000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
814660,12,7655975,1,01,1,1,4,1,1,2,...,0,0,0,0,4,0.43,0.41,3,5090167.0,5690167.0
814661,12,7655975,1,01,1,1,4,1,1,2,...,0,0,0,0,4,0.43,0.41,3,5090167.0,5690167.0
814662,12,7655975,1,01,1,1,4,1,1,2,...,0,0,0,0,4,0.43,0.41,3,5090167.0,5690167.0
814663,12,7655975,1,01,1,1,4,1,1,2,...,1500000,0,0,0,4,0.43,0.41,3,5090167.0,5690167.0
814664,12,7655975,1,01,1,1,4,1,1,2,...,0,0,22500,0,4,0.43,0.41,3,5090167.0,5690167.0

In [20]:
df['p5090']

0         3
1         3
2         3
3         2
4         2
         ..
814660    1
814661    1
814662    1
814663    1
814664    1
Name: p5090, Length: 814665, dtype: int64

In [29]:
df['mes'].value_counts()

mes
02    70077
03    69262
01    69252
04    68391
07    68263
05    68112
08    68094
06    68013
09    67185
11    66620
12    65719
10    65677
Name: count, dtype: int64

In [28]:
df[['mes', 'periodo']]

       mes   periodo
0       01  20230104
1       01  20230104
2       01  20230104
3       01  20230104
4       01  20230104
...     ..       ...
814660  12  20231249
814661  12  20231249
814662  12  20231249
814663  12  20231249
814664  12  20231249

[814665 rows x 2 columns]

In [35]:
df['periodo'].groupby(df["mes"]).value_counts()

mes  periodo
01   20230104    30735
     20230101    13204
     20230102    12780
     20230103    12533
02   20230208    31069
     20230205    13276
     20230206    13006
     20230207    12726
03   20230313    27845
     20230310    10625
     20230311    10429
     20230309    10321
     20230312    10042
04   20230417    30202
     20230415    12882
     20230414    12869
     20230416    12438
05   20230521    30268
     20230518    12737
     20230519    12671
     20230520    12436
06   20230626    27160
     20230624    10399
     20230622    10368
     20230623    10302
     20230625     9784
07   20230730    30236
     20230727    13003
     20230729    12537
     20230728    12487
08   20230835    27145
     20230831    10701
     20230832    10203
     20230833    10031
     20230834    10014
09   20230939    29866
     20230937    12679
     20230936    12591
     20230938    12049
10   20231044    26592
     20231040    10093
     20231043     9717
     20231041     9708
     20231042     9567
11   20231148    29660
     20231145    12456
     20231146    12356
     20231147    12148
12   20231252    28914
     20231249    12684
     20231250    12261
     20231251    11860
Name: count, dtype: int64

In [36]:
df['per']

0         2023
1         2023
2         2023
3         2023
4         2023
          ...
814660    2023
814661    2023
814662    2023
814663    2023
814664    2023
Name: per, Length: 814665, dtype: int64

In [ ]:
s = df["periodo"].astype("Int64").astype(str).str.zfill(8) #separating the date format into YEAR MONTH WEEK

df["year"] = s.str[:4].astype(int)
df["month"] = s.str[4:6].astype(int)
df["week"] = s.str[6:8].astype(int)

In [48]:
df[(df["year"] == 2023) & (df["month"] == 1)]

,mes,directorio,secuencia_p,regis_r010,p4000,p4010,p4020,p4030s1,p4030s1a1,p4030s2,...,iof1_i,trimestre,pctalqr,pctalqu,c_merge,ingtotug_i,ingtotugarr_i,year,month,week
10274,01,7313199,1,01,1,1,4,1,1,1,...,0,1,0.43,0.41,3,1.822500e+06,2.122500e+06,2023,1,1
285,01,7309164,1,01,2,1,4,1,2,1,...,0,1,0.43,0.41,3,3.050000e+06,3.850000e+06,2023,1,1
286,01,7309165,1,01,2,1,4,1,2,1,...,0,1,0.43,0.41,3,2.081339e+06,2.081339e+06,2023,1,1
287,01,7309165,1,01,2,1,4,1,2,1,...,0,1,0.43,0.41,3,2.081339e+06,2.081339e+06,2023,1,1
288,01,7309165,1,01,2,1,4,1,2,1,...,0,1,0.43,0.41,3,2.081339e+06,2.081339e+06,2023,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67288,01,7337286,1,01,1,1,4,1,6,1,...,0,1,0.43,0.41,3,8.829500e+06,8.829500e+06,2023,1,4
67282,01,7337283,1,01,2,1,4,1,6,1,...,0,1,0.43,0.41,3,7.062500e+06,9.062500e+06,2023,1,4
67283,01,7337283,1,01,2,1,4,1,6,1,...,0,1,0.43,0.41,3,7.062500e+06,9.062500e+06,2023,1,4
67298,01,7337290,1,01,2,1,4,1,4,1,...,0,1,0.43,0.41,3,1.973083e+07,1.973083e+07,2023,1,4
67299,01,7337290,1,01,2,1,4,1,4,1,...,0,1,0.43,0.41,3,1.973083e+07,1.973083e+07,2023,1,4

In [54]:
df["week"].groupby(df["mes"]).value_counts().sort_index()

mes  week
01   1       13204
     2       12780
     3       12533
     4       30735
02   5       13276
     6       13006
     7       12726
     8       31069
03   9       10321
     10      10625
     11      10429
     12      10042
     13      27845
04   14      12869
     15      12882
     16      12438
     17      30202
05   18      12737
     19      12671
     20      12436
     21      30268
06   22      10368
     23      10302
     24      10399
     25       9784
     26      27160
07   27      13003
     28      12487
     29      12537
     30      30236
08   31      10701
     32      10203
     33      10031
     34      10014
     35      27145
09   36      12591
     37      12679
     38      12049
     39      29866
10   40      10093
     41       9708
     42       9567
     43       9717
     44      26592
11   45      12456
     46      12356
     47      12148
     48      29660
12   49      12684
     50      12261
     51      11860
     52      28914
Name: count, dtype: int64